# Generated by Django 3.0.6 on 2020-06-02 17:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='body_txt',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.CharField(default=django.utils.timezone.now, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='pic',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='news',
            name='short_txt',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
