# Generated by Django 3.0.6 on 2020-06-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200607_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='time',
            field=models.CharField(default='00:00:00', max_length=20),
        ),
    ]
