# Generated by Django 3.0.6 on 2020-06-08 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='catid',
            new_name='cat_id',
        ),
    ]
