# Generated by Django 3.0.6 on 2020-06-08 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200609_0302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='cat_id',
            new_name='catid',
        ),
    ]
