# Generated by Django 3.0.6 on 2020-07-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20200627_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='picurl',
            field=models.TextField(default=''),
        ),
    ]
