# Generated by Django 3.0.6 on 2020-07-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20200719_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tag',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='picurl',
            field=models.TextField(default='-'),
        ),
    ]
