# Generated by Django 3.0.6 on 2020-07-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0002_auto_20200723_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='date',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='contactform',
            name='time',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
