# Generated by Django 3.0.6 on 2020-05-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_main_fb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='fb',
            field=models.TextField(default='-'),
        ),
    ]
