# Generated by Django 3.0.6 on 2020-05-31 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200601_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='fb',
        ),
        migrations.AddField(
            model_name='main',
            name='facebook',
            field=models.URLField(default='-'),
        ),
        migrations.AddField(
            model_name='main',
            name='twitter',
            field=models.URLField(default='-'),
        ),
        migrations.AddField(
            model_name='main',
            name='youtube',
            field=models.URLField(default='-'),
        ),
    ]
