# Generated by Django 3.0.6 on 2020-06-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_main_set_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='tel',
            field=models.TextField(default='Settings'),
        ),
    ]
