# Generated by Django 3.0.6 on 2020-06-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_main_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='footer_link',
            field=models.URLField(default='-'),
        ),
    ]
