# Generated by Django 3.0.6 on 2020-06-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_main_footer_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='main',
            name='set_name',
            field=models.CharField(default='Settings', max_length=30),
        ),
        migrations.AlterField(
            model_name='main',
            name='tel',
            field=models.CharField(default='00000', max_length=30),
        ),
    ]
