# Generated by Django 3.0.6 on 2020-07-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_main_picname'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='a',
            field=models.CharField(default='Settings', max_length=30),
        ),
        migrations.AddField(
            model_name='main',
            name='picurl',
            field=models.TextField(default=''),
        ),
    ]
