# Generated by Django 3.0.6 on 2020-07-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200708_0312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='a',
        ),
        migrations.AddField(
            model_name='main',
            name='picname2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='main',
            name='picurl2',
            field=models.TextField(default=''),
        ),
    ]
